export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "https://school-management-system-sms-xtgf.onrender.com/api";

export const API_ENDPOINTS = {
  LOGIN: "/api-login/",
  REFRESH: "/refresh/",
  SCHOOL: "/SchoolView/",
  STAFF: "/StaffView/",
  DEPARTMENTS: "/departments/",
  FORMS: "/forms/",
  FIELDS: "/fields/",
  CLASSES: "/getclass/",
  FORM_STATUS: "/formstatus/",
  FORM_LINK: "/admission/form/link/",
  CLASS_CATEGORY: "/classcategory/",
  SCHOOL_CLASS: "/schoolclass/",
  DIVISION_SET: "/divisionSet/",
  DIVISION_LIST: "/divisionlist/",
  SET_SUBJECT: "/setSubject/",
  SYLLABUS: "/syllabus/",
  GET_TEACHER: "/getteacher/",
  ASSIGN_CLASS: "/assignClass/",
  SEND_OTP: "/send-otp/",
  VERIFY_OTP: "/verify-otp/",
  FEATURE: "/feature/",
  GET_FEATURE: "/getfeature/",
  GET_TEMP_USER_DATA: "/gettempuserdata/",
  RAZOR_ORDER: "/razor/order/",
  PAYMENT_VERIFY: "/payment/verify/",
  GET_LOCATION: "/get-location/",
  DELETE_LOCATION: "/delete-location/",
  FACE_VERIFY: "/face-verify/",
  FACE_ENROLL: "/face-enroll/",
  ATTENDANCE: "/attendance/",
  ATTENDANCE_TODAY: "/today/",
  SALARY_COMPONENT: "/salary-component/",
  STAFF_SALARY_PAYMENT: "/staff-salary-payment/",
  FEE_TYPE: "/feetype/",
  FEE_WISE_CLASS: "/fee-wise-class/",
  DASHBOARD_COUNT: "/dashboard-count/",
  ACADEMIC_YEAR: "/main-academic-year/",
  ANNOUNCEMENT: "/announcement/",
  PARENT_CHILDREN: "/parent/children/",
  TRUSTEE_ANALYTICS: "/trustee/analytics/",
  BOARD_MEETINGS: "/board-meetings/",
  BOOKS_MANAGE: "/books/manage/",
  BOOKS_ISSUED: "/book-issued/",
  LATE_FEES: "/late-fees/",
  STUDENT_BOOKS: "/books/",
  STUDENT_MY_BOOKS: "/my-books/",
  LIBRARY_SETTINGS: "/library-settings/",
  BOOK_CATEGORIES: "/book-categories/",
  BOOK_AUTHORS: "/book-authors/",
  BOOK_PUBLISHERS: "/book-publishers/",
  LIBRARY_RACKS: "/library-racks/",
  LIBRARY_SHELVES: "/library-shelves/",
  BOOK_COPIES: "/book-copies/",
  BOOK_RESERVATIONS: "/book-reservations/",
  STUDENTS: "/get-student/",
  SUBSCRIPTION_PLANS: "/subscription-plans/",
  SUBSCRIPTIONS: "/school-subscriptions/",
  INVOICES: "/school-invoices/",
  SUBSCRIPTION_PAYMENTS: "/subscription-payments/",
  SUBSCRIPTION_AUDIT_LOGS: "/subscription-audit-logs/",
  SUBSCRIPTION_SETTINGS: "/subscription-settings/",

  ASSETS: "/asset/",
  ASSET_MAINTENANCE: "/asset-maintenance/",
  PROCUREMENT: "/procurement/",
  STOCK_ITEMS: "/stock-items/",
  STOCK_REQUEST: "/inventory-stock-request/",
  LOSS_PREVENTION: "/loss-prevention/",
  BUDGET: "/budget/",
  BUDGET_EXPENSE: "/budget-expense/",
  POST_TRACKING: "/post-tracking/",

  // Comprehensive Inventory Endpoints
  INV_CATEGORIES: "/inv-categories/",
  INV_SUBCATEGORIES: "/inv-subcategories/",
  INV_UNITS: "/inv-units/",
  INV_WAREHOUSES: "/inv-warehouses/",
  INV_SUPPLIERS: "/inv-suppliers/",
  INV_ITEMS: "/inv-items/",
  INV_ITEM_VARIANTS: "/inv-item-variants/",
  INV_BALANCES: "/inv-balances/",
  INV_TRANSACTIONS: "/inv-transactions/",
  INV_OPENING_STOCK: "/inv-opening-stock/",
  INV_PURCHASES: "/inv-purchases/",
  INV_PURCHASE_REQUESTS: "/inv-purchase-requests/",
  INV_STUDENT_ISSUES: "/inv-student-issues/",
  INV_ID_CARDS: "/inv-id-cards/",
  INV_BUNDLES: "/inv-bundles/",
  INV_RETURNS: "/inv-returns/",
  INV_ADJUSTMENTS: "/inv-adjustments/",
  INV_TRANSFER: "/inv-transfer/",
  INV_DASHBOARD_SUMMARY: "/inv-dashboard-summary/",
}

export const getWebSocketUrl = (path: string): string => {
  let baseUrl = API_BASE_URL;
  if (typeof window !== "undefined") {
    if (baseUrl.startsWith("/")) {
      baseUrl = window.location.origin + baseUrl;
    }
  }
  const wsScheme = baseUrl.startsWith("https") ? "wss://" : "ws://";
  const wsHost = baseUrl.replace(/^https?:\/\//, "").replace(/\/$/, "");
  return `${wsScheme}${wsHost}${path}`;
};

